from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(Account)
admin.site.register(Toko)
admin.site.register(Menu)
admin.site.register(KategoriMenu)
admin.site.register(Cart)
admin.site.register(CartItems)
admin.site.register(Transaction)
admin.site.register(Payment)
admin.site.register(Settlement)
admin.site.register(Discount)
admin.site.register(TableManagement)
admin.site.register(Pelanggan)
admin.site.register(Absensi)
admin.site.register(OrderType)
admin.site.register(LabelOrder)
admin.site.register(ProductPPOB)
admin.site.register(StockMenu)
admin.site.register(TrxStockMenu)
admin.site.register(WalletToko)
admin.site.register(TrxWallet)
admin.site.register(ConfirmWallet)
admin.site.register(PPOBPrepaidTransaction)
admin.site.register(TrxSubs)
admin.site.register(Pajak)
admin.site.register(ServiceFee)
admin.site.register(Banner)
admin.site.register(Article)
admin.site.register(Bank)
admin.site.register(ChanelPayment)
