# Generated by Django 3.2.7 on 2021-09-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0002_brandppob_categoryppob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanelpayment',
            name='nomer',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
