# Generated by Django 3.2.7 on 2021-09-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0003_alter_chanelpayment_nomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanelpayment',
            name='nomer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
