# Generated by Django 3.2.7 on 2021-10-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0005_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='service_fee',
            field=models.ManyToManyField(to='webadmin.ServiceFee'),
        ),
    ]
