# Generated by Django 3.2.7 on 2021-11-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0007_alter_cart_service_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
